modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory (26 is current forge version)
issueTrackerURL="https://github.com/MasterGeneral156/PotatoBlocksMod/issues"
license="https://github.com/MasterGeneral156/PotatoBlocksMod/blob/master/LICENSE"
[[mods]] #mandatory
modId="potatoblocks" #mandatory
version="1.0.0" #mandatory
displayName="Potato Blocks" #mandatory
updateJSONURL="https://raw.githubusercontent.com/MasterGeneral156/Version/master/PotatoBlocks.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/potato-blocks" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="logo.png" #optional
# A text field displayed in the mod UI
credits="idk, idaho?" #optional
# A text field displayed in the mod UI
authors="TheMasterGeneral" #optional
# The description text for the mod (multi line!) (#mandatory)
description="Compress that potato!"
[[dependencies.potatoblocks]]
    modId="ctdcore"
    mandatory=true
    versionRange="[2.1.1,]"
    ordering="BEFORE"
    side="BOTH"
